<?php
return [
    'app_name' => 'QR Transfer',
    'menu_home' => 'Home',
    'menu_about' => 'About',
    'menu_gdpr' => 'GDPR',
    'language' => 'Language',
    'welcome_message' => 'Welcome to QR Transfer',
    'about_title' => 'About QR Transfer',
    'gdpr_title' => 'Privacy Policy',
    
    // Form fields
    'beneficiary_name' => 'Beneficiary name',
    'beneficiary_iban' => 'IBAN',
    'amount' => 'Amount',
    'communication' => 'Communication',
    'generate_qr' => 'Generate QR code',
    'generated_by' => 'Generated by QR Transfer',
    'payment_to' => 'Payment to %s',
    
    // Support section
    'support_text' => 'If you like this app, you can support its development:',
    'support_thanks' => 'Thanks for supporting QR Transfer!',
    'download_qr' => 'Download QR code',
    'share_qr' => 'Share QR code',
    'cookie_notice' => 'This site uses essential cookies',
    'cookie_accept' => 'OK',
];
