<?php
return [
    'app_name' => 'QR Transfer',
    'menu_home' => 'Home',
    'menu_about' => 'About',
    'menu_gdpr' => 'GDPR',
    'language' => 'Language',
    'welcome_message' => 'Welcome to QR Transfer',
    'about_title' => 'About QR Transfer',
    'gdpr_title' => 'Privacy Policy',
    
    // Form fields
    'beneficiary_name' => 'Beneficiary Name',
    'beneficiary_iban' => 'Beneficiary IBAN',
    'amount' => 'Amount',
    'communication' => 'Communication',
    'generate_qr' => 'Generate QR Code',
    'generated_by' => 'Generated by QR Transfer',
    'payment_to' => 'Payment to %s',
    
    // Support section
    'support_text' => 'QR Transfer is free. Use the QR code below in your banking app to support us!',
    'support_thanks' => 'Thanks for QR Transfer'
];
