<?php
return [
    'app_name' => 'QR Transfer',
    'menu_home' => 'Home',
    'menu_about' => 'About',
    'menu_gdpr' => 'GDPR',
    'menu_why_us' => 'Why Us?',
    'language' => 'Language',
    'welcome_message' => 'Welcome to QR Transfer',
    'about_title' => 'About QR Transfer',
    'gdpr_title' => 'Privacy Policy & GDPR',
    'why_us_title' => 'Why Choose QR Transfer?',

    // JavaScript translations
    'error_required_fields' => 'Please fill all required fields correctly',
    'error_saving_favorite' => 'Error saving to favorites',
    'favorite_updated' => 'Favorite updated',
    'favorite_duplicate' => 'This beneficiary is already saved in your favorites',
    'favorite_saved' => 'Saved to favorites',
    'share_text' => 'Scan with your banking app!',
    'generating' => 'Generating...',
    'failed_to_generate_qr' => 'Failed to generate QR code. Please try again.',
    'invalid_format' => 'Invalid format',
    'confirm_delete_favorite' => 'Are you sure you want to delete this favorite?',
    'error_deleting_favorite' => 'Error deleting favorite',

    // Form fields
    'beneficiary_name' => 'Beneficiary Name',
    'beneficiary_iban' => 'IBAN',
    'amount' => 'Amount',
    'communication' => 'Communication',
    'generate_qr' => 'Generate QR Code',
    'generated_by' => 'Generated by QR Transfer',
    'payment_to' => 'Payment to %s',
    'clear_form' => 'Clear form',
    
    // Support section
    'support_text' => 'This app is free. If you like it, buy me a coffee by scanning the QR code below with your banking app!',
    'support_text_alt' => 'This app is free. If you like it, buy me a coffee by clicking here!',
    'support_thanks' => 'Thank you for supporting QR Transfer!',
    'download_qr' => 'Download QR Code',
    'share_qr' => 'Share QR Code',
    'cookie_notice' => 'This site uses essential cookies',
    'cookie_accept' => 'OK',

    // Why Us page
    'why_us_secure_title' => 'Secure & Private',
    'why_us_secure_text' => 'Your data is processed locally in your browser. We never store sensitive payment information on our servers.',
    'why_us_easy_title' => 'Easy to Use',
    'why_us_easy_text' => 'Generate QR codes for payments in seconds. No registration required, no complicated setup.',
    'why_us_free_title' => 'Completely Free',
    'why_us_free_text' => 'Our service is free to use, with no hidden costs or premium features.',
    'why_us_features_title' => 'Key Features',
    'why_us_feature_1' => 'Instant QR code generation for SEPA payments',
    'why_us_feature_2' => 'Support for all European banks',
    'why_us_feature_3' => 'Available in multiple languages',
    'why_us_feature_4' => 'Works on all devices - desktop, tablet, and mobile',

    // GDPR Page
    'gdpr_last_updated' => 'Last updated: %s',
    'gdpr_intro' => 'This Privacy Policy describes how QR Transfer ("we", "us", or "our") collects, uses, and protects your personal information when you use our QR code generation service.',
    
    // Information Collection
    'gdpr_info_collect_title' => 'Information We Collect',
    'gdpr_info_collect_intro' => 'We collect and process the minimum amount of information necessary to provide our service:',
    'gdpr_payment_info_title' => 'Payment Information',
    'gdpr_payment_info_desc' => 'When you generate a QR code, we process the following information:',
    'gdpr_payment_storage_note' => 'If you choose to save your payment information, it will be stored locally in your browser\'s storage. This data never leaves your device and is not accessible to us.',
    'gdpr_technical_data' => 'Technical Data',
    'gdpr_technical_data_desc' => 'We use essential cookies and local storage to ensure the proper functioning of our website.',

    // Information Usage
    'gdpr_info_use_title' => 'How We Use Your Information',
    'gdpr_info_use_intro' => 'The information you provide is used solely for:',
    'gdpr_use_qr_generation' => 'Processing your payment information to generate QR codes',
    'gdpr_use_local_storage' => 'Storing your preferred payment details locally in your browser (only if you explicitly choose this option)',
    'gdpr_use_technical' => 'Ensuring the proper technical functioning of our service',
    'gdpr_use_improvement' => 'Improving our service based on anonymous usage patterns',
    'gdpr_storage_note' => 'While we temporarily process payment information to generate QR codes, we do not permanently store this information on our servers. Any saved payment information is stored only in your browser\'s local storage if you choose to save it.',

    // Data Storage and Security
    'gdpr_security_title' => 'Data Storage and Security',
    'gdpr_security_intro' => 'QR Transfer is designed with privacy in mind:',
    'gdpr_security_processing' => 'Payment information is processed securely on our servers to generate QR codes',
    'gdpr_security_no_storage' => 'We do not permanently store payment information on our servers',
    'gdpr_security_local_storage' => 'Your saved payment details are stored only in your browser\'s local storage if you choose to save them',
    'gdpr_security_encryption' => 'We use HTTPS encryption to protect data transmission',
    'gdpr_security_standard' => 'QR codes are generated following the EPC QR standard for secure payments',
    'gdpr_security_clear_data' => 'You can clear your saved payment information at any time by clearing your browser data',

    // Cookies and Local Storage
    'gdpr_cookies_title' => 'Cookies and Local Storage',
    'gdpr_cookies_intro' => 'We use essential cookies and local storage that are necessary for the website to function properly:',
    'gdpr_cookies_section' => 'Cookies:',
    'gdpr_cookie_consent_desc' => 'Remembers your cookie preferences',
    'gdpr_cookie_language_desc' => 'Stores your preferred language setting',
    'gdpr_local_storage_section' => 'Local Storage:',
    'gdpr_local_storage_payment' => 'Stores your saved payment information (only if you choose to save it)',
    'gdpr_cookies_note' => 'These cookies and local storage data do not track you or share information with third parties. You can clear this data at any time through your browser settings.',

    // User Rights
    'gdpr_rights_title' => 'Your Rights',
    'gdpr_rights_intro' => 'Under the GDPR, you have the following rights:',
    'gdpr_right_access' => 'Right to access your data',
    'gdpr_right_rectification' => 'Right to rectification',
    'gdpr_right_erasure' => 'Right to erasure',
    'gdpr_right_restrict' => 'Right to restrict processing',
    'gdpr_right_portability' => 'Right to data portability',
    'gdpr_right_object' => 'Right to object',
    'gdpr_rights_note' => 'While we temporarily process data to generate QR codes, we don\'t permanently store personal data on our servers. Any saved data is stored locally in your browser, giving you full control through your browser settings. For any privacy-related questions, please contact us.',

    // Third-Party Services
    'gdpr_third_party_title' => 'Third-Party Services',
    'gdpr_third_party_desc' => 'Our service does not integrate with any third-party services that collect personal data. The QR codes generated are compatible with standard banking applications but the actual payment processing is handled by your bank.',

    // Policy Updates
    'gdpr_updates_title' => 'Changes to This Policy',
    'gdpr_updates_desc' => 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.',

    // Contact Information
    'gdpr_contact_title' => 'Contact Us',
    'gdpr_contact_intro' => 'If you have any questions about this Privacy Policy or our practices, please contact us:',
    'gdpr_contact_github' => 'By creating an issue on our GitHub repository',
    'select_favorite' => 'New favorite',
    'save_favorite' => 'Save as favorite',
    'update_favorite' => 'Update favorite',
    'delete_favorite' => 'Delete favorite',
];
