<?php
return [
    'beneficiary_name' => 'Beneficiary Name',
    'beneficiary_iban' => 'IBAN',
    'amount' => 'Amount',
    'communication' => 'Communication',
    'generate_qr' => 'Generate QR Code',
    'generating' => 'Generating...',
    'generating_full' => 'Generating your link...',
    'generated_by' => 'Generated by QR Transfer',
    'payment_to' => 'Payment to %s',
    'clear_form' => 'Clear form',
    'select_favorite' => 'Custom beneficiary',
    'save_favorite' => 'Save',
    'update_favorite' => 'Update',
    'delete_favorite' => 'Delete',
];
